import path from "node:path";
import { createOpenAPI } from "fumadocs-openapi/server";

// Snapshot regenerated by `just backend openapi` and checked in CI. Paths resolve from the
// docs package root (every script runs there); import.meta.dirname moves once bundled.
export const openapiSchemaPath = path.resolve(
  process.cwd(),
  "openapi/openapi.json"
);

export const openapi = createOpenAPI({
  input: [openapiSchemaPath],
});

type OpenAPIPagesOptions = NonNullable<
  Parameters<typeof openapi.staticSource>[0]
>;

// One page per operation, grouped by tag: POST /v1/auth/login -> referencia/api/auth/post-v1-auth-login
export const openapiPages: OpenAPIPagesOptions = {
  baseDir: "referencia/api",
  per: "operation",
  groupBy: "tag",
  meta: true,
  name(output) {
    if (output.type !== "operation") return output.item.name;
    const route = output.item.path
      .replace(/[{}]/g, "")
      .replace(/[^a-zA-Z0-9]+/g, "-");
    return `${output.item.method}${route}`.replace(/-+$/, "").toLowerCase();
  },
};
